export const EVENT = {
  name: "PESTAPORA",
  edition: "2026",
  venue: "Gambir Expo & Hall D2, JIExpo Kemayoran",
  dateLabel: "25-27 SEPTEMBER 2026",
  gates: "Doors 14:00 WIB",
  tier: "3 DAY PASS",
  lineup: [
    "BARASUARA",
    ".FEAST",
    "EFEK RUMAH KACA",
    "THE PANTURAS",
    "LOMBA SIHIR",
    "STARS AND RABBIT",
    "GRRRL GANG",
    "THE ADAMS",
    "MORFEM",
    "RUMAHSAKIT",
  ],
};
